### ISSUE TITLE
`z` should be have length `numBlocks`, not `numSamples`, on initialization

### ISSUE THREAD

**Issue by ech2** [csteinmetz1/pyloudnorm#18]
`numSamples` should be replaced with `numBlocks`: https://github.com/csteinmetz1/pyloudnorm/blob/812bce142f85cf8b0992a908f80466f42166f5dd/pyloudnorm/meter.py#L73

**Comment by csteinmetz1** [comment]
Thanks for pointing this out. This should not have caused any issues but I have corrected it for transparency/readability. Thanks again!
