### ISSUE TITLE
README correction IIRfilter not IIRFilter

### ISSUE THREAD

**Issue by RBBlackstone** [csteinmetz1/pyloudnorm#21]
Under Advanced operation
the 'f' is lower case or it won't load.

OLD. from pyloudnorm import IIRFilter

NEW.  from pyloudnorm import IIRfilter

**Comment by csteinmetz1** [comment]
Thanks @RBBlackstone! Fixed in #22

**Comment by RBBlackstone** [comment]
Wow, that was fast.

Diggin your music.  Long time (since 2" tape and vinyl) recording engineer/musician here.

Sent a Facebook friend request as well.

Take care,
RB
