### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by faroit** [csteinmetz1/pyloudnorm#26]
this package is super useful, have you considered uploading it to pypi?

**Comment by csteinmetz1** [comment]
Thanks @faroit. The package is actually on pypi already ([https://pypi.org/project/pyloudnorm/](https://pypi.org/project/pyloudnorm/)) but I haven't shown this in the README. I will make an update to reflect that. In the past I have been slow to update the package on pypi, but there has been increased interest.

**Comment by faroit** [comment]
Cool. Thanks. Will add this to the awesome scientific python list
