### ISSUE TITLE
Center frequency for high shelf filter may be wrong

### ISSUE THREAD

**Issue by schtschenok** [csteinmetz1/pyloudnorm#3]
I think that high shelf center frequency should be 1500 Hz, not 1681.9 Hz.
I may be wrong, but I think 1500 Hz with this function for recalculating coefficients corresponds much better to the original biquad filter values from BS.1770-4.
I've attached the image with frequency responses.
Green line - 1500 Hz center frequency.
Blue line - 1681.9 Hz.
Red line - original values from BS.1770-4.
![image](https://user-images.githubusercontent.com/22475452/39965811-ee4de0b8-56a8-11e8-8c2d-44ec265a0888.png)

**Comment by csteinmetz1** [comment]
I spent some time researching this again. When I first set up this library I was unsure of the proper filter parameters but made my selection based on the results in this [paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.725.3873&rep=rep1&type=pdf) (See page 4). What I have now discovered is that the formulas I am using for the generation of the coefficients differs from the one used in their paper. I am using formulas that originate from the [Audio EQ Cookbook](http://www.musicdsp.org/files/Audio-EQ-Cookbook.txt) which defines the cutoff frequency differently. Therefore you are correct that Fc = 1500 kHz with these formulas and I have made this change. Thank you!

P.S. I have also noticed that LUFS measurements do not perfectly agree with other loudness meters with some audio inputs. I have not been able to track down where this is occurring. See Issue #4.
