### ISSUE TITLE
Local install on Windows fails due to bad character in README.md

### ISSUE THREAD

**Issue by f-brinkmann** [csteinmetz1/pyloudnorm#44]
I wanted to locally install the package after cloning it so I could play around with the code using `pip install -e .` This gave the error

```
File "C:\Users\panik\Documents\Code\Toolboxes\pyloudnorm\setup.py", line 4, in <module>
          long_description = fh.read()
File "C:\Users\panik\anaconda3\envs\pyloudnorm\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4038: character maps to <undefined>
```

There seems to be some sort of bad character in README.md, which might be a Windows only problem. Local install works if I replace the lines from README

```python
with open("README.md", "r") as fh:
     long_description = fh.read()
```

by

```python
long_description = "test"
```

**Comment by csteinmetz1** [comment]
Hi @f-brinkmann,

I have just pushed a new release that tries to address this issue. Could you give it a try and let me know if it works for you? I currently do not have a Windows environment for testing. Thanks!

**Comment by f-brinkmann** [comment]
yes, now it works thanks :)
