### ISSUE TITLE
Handling inputs shorter than 400ms

### ISSUE THREAD

**Issue by schtschenok** [csteinmetz1/pyloudnorm#5]
I saw this in your todo list, and I have a suggestion for you.
According to EBU TECH 3341, "There may be cases where it is relevant to use other window lengths or time constants than those specified above."
So, the solution I see - is just making window smaller for short inputs, because 400ms window not only don't work on inputs shorter than 400ms, but actually produces bad results on inputs shorter than few seconds. By "bad results" I mean LUFS values that doesn't match to subjective loudness, but yes, fully compliant to the standard.

P.S. I have a couple of more suggestions and thoughts about this project, and if you are interested, maybe I could contact you somehow via facebook or email?

**Comment by csteinmetz1** [comment]
Thank you. I will experiment with using shorter block lengths on inputs shorter than 400 ms and report the results here. 

I noted in Adobe Audtion, they always follow the specification, and when you analyze an input shorter than 400 ms they display an error indicating the input was too short. This may also be an option.  

Thanks again for your help and I would love to chat more about the project. You can reach me at cjstein@clemson.edu.

**Comment by csteinmetz1** [comment]
I have created a new branch called [meter](/csteinmetz1/pyloudnorm/tree/meter). This includes a new class called `Meter` that allows the user to set certain parameters for their meter when instantiated allowing for more control. The user can now choose from different frequency weighting filters (note: the new filters still need to be implemented) or even implement their own custom filter if they so desire. Related to this issue, it also allows the block size (or window size) to be set by the user when instantiating a Meter object. This is still in its early stages and will remain on its own branch until we feel that the functionality is clean enough to merge to master. 

Also note that this change requires new syntax when measuring loudness. This example shows how to use the new class with a BS.1770-4 meter. 
```
import pyloudnorm.loudness
import pyloudnorm.util

rate, data = scipy.io.wavfile.read("audio.wav")
song = util.validate_input_data(data, rate)
meter = loudness.Meter(rate)
song_loudness = meter.measure_gated_loudness(song)
```
This example shows how to instantiate a meter using the Fentron/Lee 1 filter and a block size of 100 ms.
```
import pyloudnorm.loudness
import pyloudnorm.util

rate, data = scipy.io.wavfile.read("audio.wav")
song = util.validate_input_data(data, rate)
meter = loudness.Meter(rate, filter_class='Fenton/Lee 1', block_size=0.100)
song_loudness = meter.measure_gated_loudness(song)
```
