### ISSUE TITLE
Input value range for data?

### ISSUE THREAD

**Issue by Franky1** [csteinmetz1/pyloudnorm#58]
Wave audiofiles are often created with **int16** audio data, but `pyloudnorm` seems to require **float** arrays as input for the `data` arguments.

How do the float values have to be scaled respectively what is the maximum numerical **range** for the full scale so that the calculations by `pyloudnorm` make sense?

Is it `[+1.0; -1.0]` in float?

**Comment by iver56** [comment]
Yes, the -1 to +1 range is common for float32 audio arrays. It is common to process audio in float32 even though the storage format is something different (e.g. int16 wav)
