### ISSUE TITLE
Exception in integrated_loudness

### ISSUE THREAD

**Issue by peastman** [csteinmetz1/pyloudnorm#9]
When I call `integrated_loudness()` I get the following exception:

```
  File "/Users/peastman/sampler/pyloudnorm/meter.py", line 125, in integrated_loudness
    z_avg_gated = np.nan_to_num([np.mean([z[i,j] for j in J_g]) for i in range(numChannels)])
  File "/Users/peastman/anaconda/lib/python3.4/site-packages/numpy/lib/type_check.py", line 369, in nan_to_num
    if not y.shape:
AttributeError: 'list' object has no attribute 'shape'
```

This can be fixed by changing line 125 of meter.py to

```python
z_avg_gated = np.nan_to_num(np.array([np.mean([z[i,j] for j in J_g]) for i in range(numChannels)]))
```

**Comment by csteinmetz1** [comment]
Hi, thanks for your interest in pyloudnorm!

I haven't run into this error before so I took a look at the where the code was breaking in numpy. Here is the code of `nan_to_num()` in the latest release version of numpy (v1.14.5)

```python
def nan_to_num(x, copy=True):
    x = _nx.array(x, subok=True, copy=copy)
    xtype = x.dtype.type
    if not issubclass(xtype, _nx.inexact):
        return x

    iscomplex = issubclass(xtype, _nx.complexfloating)
    isscalar = (x.ndim == 0)

    x = x[None] if isscalar else x
    dest = (x.real, x.imag) if iscomplex else (x,)
    maxf, minf = _getmaxmin(x.real.dtype)
    for d in dest:
        _nx.copyto(d, 0.0, where=isnan(d))
        _nx.copyto(d, maxf, where=isposinf(d))
        _nx.copyto(d, minf, where=isneginf(d))
    return x[0] if isscalar else x
```

From my understanding the input `x` is actually cast to a ndarray in the function and the parameter `x` need only be array_like and not an ndarray. That means passing the result of the list comprehension in pyloudnorm should be valid. My guess is that you are using an older version of numpy. 

The traceback indicates the code breaks on line 369 at 
```python
if not y.shape:
```
which I don't see in `nan_to_num` in the recent version of numpy. 

Let me know what version of numpy you are using and I recommend upgrading to the latest release and seeing if that resolves the issue. Hope this helps and comment back with your results and I will close this if an upgrade works for you.  Thanks!

**Comment by peastman** [comment]
Thanks!  I have NumPy 1.8.1 installed, which is a somewhat old version.  That's what originally came with my Python distribution.  I tend to avoid upgrading core Python packages unless absolutely necessary, since it very often causes things to break.  The change I suggested above should be very safe, and will allow it to work on older versions as well.

**Comment by csteinmetz1** [comment]
In this case it is easy to add in support so I went ahead and did so. This change has now been merged with master. Although, I can't guarantee support of future functionality with older versions of numpy. 

I would ultimately recommend upgrading numpy as you then ensure compatibility with new packages in development (like pyloudnorm) and you get the benefits of new versions (greater efficiency, better structure, new features, etc.) They tend to maintain backwards compatibility quite well so even packages written for older versions (like 1.8.1) will still function until they move to 2.0.0 and above.

On a related note, I would recommend checking out [virtual environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/) if you are worried about affecting dependancies for your own projects. Using virtual environments will allow you to leave your stock Python site-packages directory untouched while using new packages in your virtual environment.

Thanks again and please open an issue (or open a PR) if you run into any problems or have feature recommendations.
